version: '3.7'

services:
  app:
    container_name: flowback_app
    build: .
    volumes:
      - ./:/code
    #command: python /flowbck/tensorai_root/manage.py runserver 0.0.0.0:8000
    command: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python /code/tensorai_root/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
    links:
      - db
  db:
    container_name: flowback_db
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
