# Generated by Django 2.1.4 on 2019-01-07 00:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Well_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateTimeField()),
                ('data_time', models.DateTimeField()),
                ('data_tubing_psi', models.IntegerField()),
                ('data_csg_psi', models.IntegerField()),
                ('data_choke_size', models.IntegerField()),
                ('data_sep_psi', models.IntegerField()),
                ('data_oil_rate', models.IntegerField()),
                ('data_water_rate', models.IntegerField()),
                ('data_gas_rate', models.IntegerField()),
                ('data_flowline_psi', models.IntegerField()),
                ('data_chlorides', models.IntegerField()),
                ('data_sand_percent', models.IntegerField()),
                ('data_h2s', models.IntegerField()),
                ('data_remarks', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Well_Profile',
            fields=[
                ('company', models.CharField(choices=[('Oxy', 'Oxy'), ('Riverbend', 'Riverbend'), ('Concho', 'Concho')], default='', max_length=100)),
                ('well_name', models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False)),
                ('API10', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('prod_path', models.CharField(choices=[('production casing', 'production casing'), ('production tubing', 'production tubing')], default='', max_length=100)),
                ('prod_path_diameter', models.IntegerField()),
                ('team', models.CharField(choices=[('Asset team 1', 'Asset team 1'), ('Asset team 2', 'Asset team 2'), ('Asset team 3', 'Asset team 3')], default='', max_length=100)),
                ('formation', models.CharField(choices=[('WCA', 'WCA'), ('WCB', 'WCB'), ('WCC', 'WCC'), ('1BS', '1BS'), ('2BS', '2BS'), ('3BS', '3BS'), ('HOBAN', 'HOBAN')], default='', max_length=100)),
                ('asset', models.CharField(choices=[('TX Asset 1', 'TX Asset 1'), ('TX Asset 2', 'TX Asset 2'), ('NM Asset 1', 'NM Asset 1'), ('NM Asset 2', 'NM Aseet 2')], default='', max_length=100)),
                ('region', models.CharField(choices=[('TX Delaware Basin', 'Tx Delaware Basin'), ('Midland Basin', 'Midland Basin'), ('NM Delaware Basin', 'NM Delaware Basin')], default='', max_length=100)),
                ('flowback_company', models.CharField(default='', max_length=100)),
                ('flowback_start_date', models.DateTimeField()),
                ('contractor_name', models.CharField(default='', max_length=100)),
                ('contractor_phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. 10 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('facility', models.CharField(default='', max_length=100)),
                ('initial_shut_in_psi', models.IntegerField()),
                ('initial_res_psi', models.IntegerField()),
                ('total_frac_fluid', models.IntegerField()),
                ('total_sand_pumped', models.IntegerField()),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_updated', models.DateTimeField(editable=False, null=True)),
                ('engineer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='well_data',
            name='data_well_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowback.Well_Profile'),
        ),
    ]
