# Generated by Django 2.1.4 on 2019-01-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well_data',
            name='data_time',
        ),
        migrations.AddField(
            model_name='well_data',
            name='data_hour',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well_data',
            name='data_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
