# Generated by Django 2.1.4 on 2019-01-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowback', '0003_remove_well_data_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='well_data',
            name='gas_24hr',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well_data',
            name='gor',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well_data',
            name='inverse_fluid_pi',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well_data',
            name='inverse_oil_pi',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well_data',
            name='liquid_productivity_index',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well_data',
            name='oil_24hr',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well_data',
            name='oil_productivity_index',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well_data',
            name='total_fluid_24hr',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well_data',
            name='total_fluid_hrly',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well_data',
            name='water_24hr',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well_data',
            name='wcut',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
    ]
