# Generated by Django 2.1.4 on 2019-01-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowback', '0004_auto_20190106_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well_data',
            name='gas_24hr',
        ),
        migrations.RemoveField(
            model_name='well_data',
            name='gor',
        ),
        migrations.RemoveField(
            model_name='well_data',
            name='inverse_fluid_pi',
        ),
        migrations.RemoveField(
            model_name='well_data',
            name='inverse_oil_pi',
        ),
        migrations.RemoveField(
            model_name='well_data',
            name='liquid_productivity_index',
        ),
        migrations.RemoveField(
            model_name='well_data',
            name='oil_24hr',
        ),
        migrations.RemoveField(
            model_name='well_data',
            name='oil_productivity_index',
        ),
        migrations.RemoveField(
            model_name='well_data',
            name='total_fluid_24hr',
        ),
        migrations.RemoveField(
            model_name='well_data',
            name='water_24hr',
        ),
        migrations.RemoveField(
            model_name='well_data',
            name='wcut',
        ),
        migrations.AlterField(
            model_name='well_data',
            name='total_fluid_hrly',
            field=models.IntegerField(editable=False),
        ),
    ]
