# Generated by Django 2.1.4 on 2019-01-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowback', '0005_auto_20190106_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well_data',
            name='total_fluid_hrly',
        ),
    ]
